version: '3'

services:
  app:
    container_name: app-databases
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9090:9090"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/alex
      - SPRING_DATASOURCE_USERNAME=alex
      - SPRING_DATASOURCE_PASSWORD=alex
      - SPRING_DATASOURCE_DRIVER_CLASS_NAME=org.postgresql.Driver
      - SPRING_JPA_DATABASE_PLATFORM=org.hibernate.dialect.PostgreSQLDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
        - app_network

  database:
    image: postgres:15-alpine
    container_name: postgreSQL-database
    env_file:
      - database.env
    ports:
      - "6543:5432"
    volumes:
      - database-data:/var/lib/postgresql/data/
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  database-data: